pref("extensions.moment.background", "#FAFAFA");
pref("extensions.moment.text", "#424242");
pref("extensions.moment.temp", "c");
pref("extensions.moment.expires", "Sun, 21 Oct 2012 03:55:00 GMT");
pref("extensions.moment.weather", "Light Rain Showers");
pref("extensions.moment.degrees", "7");
pref("extensions.moment.loc", "");
pref("extensions.moment.tform", "H M S");
pref("extensions.moment.dform", "D M Y");
pref("extensions.moment.clock", "24");
pref("extensions.moment.font", "100");
pref("extensions.moment.zero", "y");
pref("extensions.moment.css", "");