pref("extensions.moment.background", "#FFFFFF");
pref("extensions.moment.text", "#003D51");
pref("extensions.moment.temp", "C");
pref("extensions.moment.expires", "Sun, 21 Oct 2012 03:55:00 GMT");
pref("extensions.moment.weather", "Light Rain Showers");
pref("extensions.moment.degrees", "7");
pref("extensions.moment.loc", ":auto");
pref("extensions.moment.tform", "H M S");
pref("extensions.moment.dform", "D M Y");
pref("extensions.moment.clock", "24");